### ISSUE TITLE
Question for Weighted Motion Regularization

### ISSUE THREAD

**Issue by RickyYXY** [POSTECH-CVLab/RoDyGS#1]
Hi,
In your paper, you have mentioned that:
_The regularization weight w_i adjusts the strength of regularization and varies based on the value of a cumulative exponential function as i changes._
But I can't find how w_i can be calculated in your paper.
Can you provide a detail about how to get w_i?

Thks.

**Comment by Slime0519** [comment]
Thank you for your question. Motion basis regularization weight is calculated using the cumulative exponential function. Here’s the Python code to compute weight:

```python
import numpy as np

def get_cumulative_exponential_weight(num_basis=16, dist_max=3):
    x = np.linspace(0, dist_max, num_basis)
    reg_weight = np.cumsum(np.exp(-x))
    
    # normalize y
    reg_weight = reg_weight / np.sum(reg_weight) * num_basis
    
    return reg_weight
```
This function returns the regularization weights for each motion basis. You can adjust the number of weights (num_weight) for different number of basis.
